name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.2'
    env:
      TEST_ACL: ${{ secrets.TEST_ACL }}
      TEST_BUCKET: ${{ secrets.TEST_BUCKET }}
      TEST_REGION: ${{ secrets.TEST_REGION }}
      TEST_ACCESS_KEY: ${{ secrets.TEST_ACCESS_KEY }}
      TEST_SECRET_KEY: ${{ secrets.TEST_SECRET_KEY }}
      TEST_FOLDER: ${{ secrets.TEST_FOLDER }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake